### ISSUE TITLE
Problem with torchsearchsorted

### ISSUE THREAD

**Issue by ghost** [DarlingHang/st-nerf#1]
Hello,

I cannot install the torchsearchsorted package, the following error is returned : 

> Failed to build torchsearchsorted
> Installing collected packages: torchsearchsorted
>     Running setup.py install for torchsearchsorted ... error

Do you know what the error might be?

**Comment by DarlingHang** [comment]
Hello, now pytorch has implement searchsorted and torchsearchsorted is no longer a dependency. We have removed this dependency in a latest commit.
