### ISSUE TITLE
can't download the demo dataset

### ISSUE THREAD

**Issue by sycamore27** [DarlingHang/st-nerf#11]
The link https://drive.google.com/drive/folders/13YHw_YSGewvcgYdwqbelM9L2JiPNWLi7 seems empty, and I can't download the dataset. Could you please update the link and share the dataset? Thanks very much!

**Comment by Jiakai-Zhang** [comment]
Closed as we have re-uploaded the dataset to Baidu Netdisk :) Feel free to re-open it if there are further problems.
