### ISSUE TITLE
Can't download dataset from Baidu

### ISSUE THREAD

**Issue by iSach** [DarlingHang/st-nerf#13]
Hello,

I am trying to download the dataset from the Baidu drive, but it asks me to use the Netdisk client which tells me to log in with a Baidu account. It seems impossible for me to create a Baidu account with a belgian (+32) phone number.

Is it possible to upload the dataset to some other public drive (google, etc)? Or maybe do you have an idea for how I could download it from that drive when being outside of China?

Thanks in advance.

**Comment by DarlingHang** [comment]
Thanks for reaching out. We just updated the download link and please have a look.

**Comment by iSach** [comment]
> Thanks for reaching out. We just updated the download link and please have a look.

Hello, thanks a lot for the fast reply and solution!! Awesome work by the way, really incredible results it was really impressive to read!

Best regards
