### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by flynnamy** [DarlingHang/st-nerf#2]
Hi，it seems that VIEW_MASK should be setted as not none! How to solve this problem? @DarlingHang 
![image](https://user-images.githubusercontent.com/20398890/127740450-f952b781-1e8d-4360-827e-9e13b2cd3a43.png)

**Comment by DarlingHang** [comment]
What's your yacs's version? We have tested our codes on yacs-0.1.8.

**Comment by flynnamy** [comment]
Thanks!I update yacs,it is ok.But it has new error like this.How to solve it? @DarlingHang 
![image](https://user-images.githubusercontent.com/20398890/127879275-51dc04a8-2e29-4edf-a9a1-d177961c2ffe.png)

**Comment by DarlingHang** [comment]
This is an issue about PyTorch version. I guess change this line to "inds = torch.searchsorted(cdf,u,right=True)" will work.

**Comment by flynnamy** [comment]
Thanks! It works! If it could be faster,it will be better!
