### ISSUE TITLE
may I know how to setup your camera system and the configuration information? thanks a lot

### ISSUE THREAD

**Issue by semchan** [DarlingHang/st-nerf#5]

**Comment by DarlingHang** [comment]
What do you mean by "setup"?

**Comment by semchan** [comment]
> What do you mean by "setup"?
Thank you. For example, what kind of camera do you need? Do all cameras have to be the same model, the same exposure time, etc? Do you need to trigger synchronization when shooting? Thanks a lot.

**Comment by DarlingHang** [comment]
I think it can work as long as the camera system is synchronized and calibrated.

**Comment by Jiakai-Zhang** [comment]
> > What do you mean by "setup"?
> > Thank you. For example, what kind of camera do you need? Do all cameras have to be the same model, the same exposure time, etc? Do you need to trigger synchronization when shooting? Thanks a lot.

I am happy to add more details of our setup. We use 16 sync and pre-calibrated 4K Z-CAM. We previously set them in the same exposure time and ISO and all other settings. We manually adjust the focal length of each camera to make the performer is in focus. We also remove the distortion for each camera considering the distortion is a little severe.
